version: "3"
services:
  # Create a service called spark-master
  spark-master:
    image: "sdesilva26/spark_master:0.0.2"
    ports:
      - "8080:8080"
    networks:
      - spark-net
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==master
  # Create a second service called spark-worker
  spark-worker:
    image: "sdesilva26/spark_worker:0.0.2"
    ports:
      - "9091:9091"
    environment:
      - CORES=3
      - MEMORY=15G
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==worker
      # Deploy 3 containers for this service
      replicas: 3
    networks:
      - spark-net
# Create the spark-net network
networks:
  spark-net:
    driver: overlay
